### ISSUE TITLE
Connection not establishing

### ISSUE THREAD

**Issue by motivforz** [Steppschuh/RemoteControlServer#82]
Just upgraded to the latest app (on Nexus 4 stock android v5.0.1), and the mouse no longer worked. Updated the server on Windows 7 PC to version 2.0.1.60, same issue. Ran cmd ping from PC to phone IP which was successful. 

Remote Control Server states no connection, but blue light is flashing when screen pressed on mouse/keyboard in app, just has no effect on typing or moving or clicking the mouse. 

Log reads as follows (displays mouse moves/clicks on my pc but here it is missing evidence of moving mouse in this post): 

Error while reading data
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Remote_Control_Server.RCS_Start.Timer_Listen_Tick(Object sender, EventArgs e)
Error while reading data
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Remote_Control_Server.RCS_Start.Timer_Listen_Tick(Object sender, EventArgs e)
Error while reading data
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Remote_Control_Server.RCS_Start.Timer_Listen_Tick(Object sender, EventArgs e)
Error while reading data
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at Remote_Control_Server.RCS_Start.Timer_Listen_Tick(Object sender, EventArgs e)


























**Comment by Steppschuh** [comment]
The server version you are using is outdated and not compatible with the latest app version. Please get the latest version from here:
https://github.com/Steppschuh/RemoteControlServer/releases
